version: 2.1

orbs:   # Reusable modules of config logic
  ruby: circleci/ruby@1.1.0
  node: circleci/node@2

workflows:    # Collection of jobs orchestrated to run in a specific order
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - approve_deploy:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - approve_deploy

jobs: # Collection of commands needed to accomplish a specific task
  build:
    docker:   # Supported environments include Windows, macOS, Linux, and Docker
      - image: cimg/ruby:2.7-node   # Convenience images optimized for performance
    resource_class: xlarge    # Options range from small to 2xl+
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
  test:
    parallelism: 5    # Split tests across multiple nodes
    docker:
      - image: cimg/ruby:2.7-node
      - image: circleci/postgres:9.5-alpine   # Load sidecar images to extend execution environment
        environment:
          POSTGRES_USER: circleci-demo-ruby
          POSTGRES_DB: rails_blog_test
          POSTGRES_PASSWORD: ""
    resource_class: xlarge
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: circleci-demo-ruby
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - ruby/rspec-test
      - ruby/rubocop-check
  deploy:
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
